#!/bin/zsh

DOT_FILES_DIR=$(dirname $(realpath -s $0))

ln -s $DOT_FILES_DIR/zshrc .zshrc
ln -s $DOT_FILES_DIR/zsh .zsh

ln -s $DOT_FILES_DIR/gitconfig .gitconfig
ln -s $DOT_FILES_DIR/gitignore .gitignore

ln -s $DOT_FILES_DIR/agignore .agignore
ln -s $DOT_FILES_DIR/gemrc .gemrc
ln -s $DOT_FILES_DIR/pryrc .pryrc
ln -s $DOT_FILES_DIR/psqlrc .psqlrc
ln -s $DOT_FILES_DIR/tmux.conf .tmux.conf

ln -s $DOT_FILES_DIR/init.lua .config/nvim/init.lua
ln -s $DOT_FILES_DIR/lua .config/nvim/lua

touch .zshrc.local
