#!/bin/zsh

set -e

DIR=$(dirname $(realpath -s $0))

ln -s $DIR/wezterm.lua .wezterm.lua

ln -s $DIR/zsh .zsh
ln -s $DIR/zshrc .zshrc

ln -s $DIR/gitconfig .gitconfig
ln -s $DIR/gitignore .gitignore

ln -s $DIR/mise.config.toml .config/mise/config.toml

ln -s $DIR/lsp .config/nvim/lsp
ln -s $DIR/lua .config/nvim/lua
ln -s $DIR/init.lua .config/nvim/init.lua

ln -s $DIR/gemrc .gemrc
ln -s $DIR/pryrc .pryrc
ln -s $DIR/psqlrc .psqlrc
ln -s $DIR/agignore .agignore

touch .zshrc.local
