local o = vim.o
o.autowrite = true
o.backup = false
o.breakindent = true
o.completeopt = 'menuone,noselect'
o.diffopt = 'internal,filler,closeoff,vertical'
o.encoding = 'utf-8'
o.foldexpr = 'nvim_treesitter#foldexpr()'
o.foldmethod = 'expr'
o.gdefault = true
o.grepprg = 'ag --nogroup --nocolor'
o.ignorecase = true
o.history = 50
o.listchars = 'tab:  '
o.modelines = 0
o.scrolloff = 10
o.secure = true
o.shell = '/bin/zsh'
o.shiftround = true
o.smartcase = true
o.splitbelow = true
o.splitright = true
o.termguicolors = true
o.timeoutlen = 500
o.wildignore = 'tmp/**,log/**'
o.wildmode = 'list:longest,list:full'
o.writebackup = false

local w = vim.wo
w.list = true
w.foldenable = false
w.number = true
w.numberwidth = 5
w.relativenumber = true
w.signcolumn = 'yes'
w.wrap = false

local b = vim.bo
b.expandtab = true
b.modeline = false
b.shiftwidth = 2
b.softtabstop = 2
b.swapfile = false
b.tabstop = 2
b.textwidth = 120
