local o = vim.o
o.autowrite = true
o.breakindent = true
o.cursorline = true
o.diffopt = 'internal,filler,closeoff,vertical'
o.foldexpr = 'v:lua.vim.treesitter.foldexpr()'
o.foldmethod = 'expr'
o.gdefault = true
o.grepprg = 'rg --vimgrep --smart-case'
o.inccommand = 'split'
o.ignorecase = true
o.history = 50
o.listchars = 'tab: » ,trail:·,nbsp:␣'
o.modelines = 0
o.scrolloff = 10
o.secure = true
o.shell = '/bin/zsh'
o.shiftround = true
o.smartcase = true
o.splitbelow = true
o.splitright = true
o.showmode = false
o.signcolumn = 'yes'
o.timeoutlen = 300
o.ttimeoutlen = 100
o.updatetime = 250
o.wildignore = 'tmp/**,log/**'
o.wildmode = 'list:longest,list:full'
o.writebackup = false

o.list = true
o.foldenable = false
o.number = true
o.numberwidth = 5
o.relativenumber = true
o.wrap = false

o.expandtab = true
o.modeline = false
o.shiftwidth = 2
o.softtabstop = 2
o.swapfile = false
o.tabstop = 2
o.textwidth = 120
