alias ls="ls -FGh"
alias sed="sed -E"
alias rmq="brew services restart rabbitmq"
alias rds="brew services restart redis"
alias tdl="tail -f log/development.log"
alias lim="vim -u ~/.vimrc.light"
alias ctags="`brew --prefix`/bin/ctags"
alias prc="hub pr checkout "
