alias ls="ls -FGh"
alias ll="ls -la"
alias ctags="`brew --prefix`/bin/ctags"
alias sed="sed -E"
alias rrmq="brew services restart rabbitmq"
alias rrds="brew services restart redis"
alias tdl="tail -f log/development.log"
alias lvim="vim -u ~/.vimrc.light"
