alias qq="cd . && source ~/.zshrc"
alias ls="ls -FGh"
alias ll="ls -la"
alias ctags="`brew --prefix`/bin/ctags"
alias gph="git push heroku master && heroku run rake db:migrate && heroku restart"
alias sed="sed -E"
